---
namespace: ansi_colle
name: mods
version: 1.3.2
readme: README.md

authors:
  - Chun Pan Yung

description: Collections of various plugins and modules

license:
  - MIT

tags:
  - windows
  - linux
  - tools

dependencies:
  "community.general": "*"
  "ansible.windows": "*"

repository: https://github.com/ChunPanYung/ansi_colle-mods
