---
namespace: ansi_colle
name: mods
version: 1.3.0
readme: README.md

authors:
  - Chun Pan Yung

description: Collections of various plugins and modules

license:
  - MIT

tags:
  - windows
  - linux
  - tools

dependencies: {}

repository: https://github.com/ChunPanYung/ansi_colle-mods
