---
# tasks file for github_release
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_release_repo }}/releases/latest"
    return_content: true
  register: __github_api

- name: Check package version
  ansi_colle.mods.cmp_pkg:
    name: "{{ github_release_get_cmd }}"
    desired_version: "{{ __github_api.json.tag_name[1:] }}"
  register: __cmp_output

- name: Execute the following if version is not the latest
  when: (__cmp_output.rc == 2) or (__cmp_output.rc == 3)
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: __tempdir

    - name: Download executables for linux x64 system
      ansible.builtin.get_url:
        url: "{{ __cmp_output.json.assets[release_asset_index].browser_download_url }}"
        dest: "{{ __tempdir.path }}/"
        mode: '0644'

    - name: Move file to destination if download_type is 'move_to_destination'
      when: download_type == 'move_to_destination'
      become: "{{ github_release_sudo_privilege }}"
      ansible.builtin.copy:
        src: "{{ __tempdir.path }}/"
        dest: "{{ github_release_destination }}/"
        remote_src: true
        mode: "{{ github_release_cmd_mode }}"
        owner: "{{ github_release_cmd_owner | default(omit) }}"
        group: "{{ github_release_cmd_group | default(omit) }}"

    - name: Extract file to destination if download_type is 'extract_and_move'
      become: "{{ sudo_privilege }}"
      when: download_type == 'extract_and_move'
      ansible.builtin.unarchive:
        src: "{{ __tempdir.path }}/"
        dest: "{{ github_release_destination }}/"
        remote_src: true
        mode: "{{ github_release_cmd_mode }}"
        owner: "{{ github_release_cmd_owner | default(omit) }}"
        group: "{{ github_release_cmd_group | default(omit) }}"

    - name: Remove temp directory
      when: download_type != 'download_only'
      ansible.builtin.file:
        path: "{{ __tempdir.path }}"
        state: absent

    - name: Return variable containing downloaded file path
      when: download_type == 'download_only'
      ansible.builtin.set_fact:
        cmd_from_github_rv: "{{ __tempdir.path }}"
