---
argument_specs:
  main:
    short_description: Main entry for the cmd_from_github.
    description:
      - This role will compare existing command version to version from github using api.
      - It will download file from github if command does not exist, or new versiond detected.
      - It will move to destination specifed, or you can supply download only option.
      - All return value will be saved in a variable call cmd_from_github_rv, type dict.
      - It only support Linux.
    author:
      - Chun Pan Yung
    options:
      get_cmd_version:
        type: "str"
        required: true
        description:
          - Complete command to get the currenct command version.
          - It will use provided command to get currenct command version.
          - It only take 2 words.
      github_repo:
        type: "str"
        required: true
        description:
          - Using github REST API endpoints for getting latest release.
          - Supply only the owner and repo name in the form of '{owner}/{repo}'.
      cmd_mode:
        type: str
        required: false
        default: "0755"
        description:
          - Default cmd permission.
      cmd_owner:
        type: "str"
        required: false
        default: "root"
        description:
          - Default cmd owner.
      cmd_group:
        type: "str"
        required: false
        default: "root"
        description:
          - Default cmd group.
      release_asset_index:
        type: "int"
        required: false
        default: 0
        description:
          - Asset index number from latest github release page.
          - It always starts with 0.
          - First item is 0, second item is 1, and third item is 3 etc.
      download_type:
        type: "str"
        required: false
        default: "move_to_desination"
        choices:
          - move_to_destination
          - download_only
          - extract_and_move
        description:
          - Where should the cmd goes after download.
          - move_to_destionation, will move according to value of 'cmd_destination'.
          - extract_and_move, will move according to value of 'cmd_destination' after extracting cmd.
          - download_only, download file only and return download file path, ignore value from 'cmd_destination'.
      cmd_destination:
        type: "str"
        required: false
        default: "/usr/local/bin"
        description:
          - Where should the cmd goes after download.
          - This value is ignored if 'download_type' == 'download_only'.
