---
- name: Install collections and roles
  hosts: localhost
  connection: local
  tasks:
    - name: Install community collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop:
        - community.general
        - ansible.windows

    - name: Install this collection
      vars:
        this_collection: git+https://github.com/ChunPanYung/ansi_colle-mods.git
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ this_collection }},{{ git_version | default('main') }}"
