---
- name: Ping test
  hosts: all
  tasks:
    - name: Execute linux ping test, execute windows ping test if fail
      block:
        - name: Linux ping test
          ansible.builtin.ping:
      rescue:
        - name: Windows ping test
          ansible.windows.win_ping:
