---
- name: Test plugins export_xlsx
  hosts: localhost
  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Test - download binary only
      vars:
        github_repo: "k3d-io/k3d"
        release_asset_index: 4
        download_type: "download_only"
